# Site settings
title: Chris Jordan
email: cjordan@8thlight.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my blog. I am a Resident Apprentice at 8th Light in London.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  c-j-j

# Build settings
markdown: kramdown
paginate: 10
